services:
  bot:
    build: .
    restart: unless-stopped
    network_mode: host  # Use host networking to access ComfyUI
    user: "${CURRENT_UID:-1000}:${DOCKER_GID:-999}"  # Use host user's UID and docker group GID
    volumes:
      - ./.env:/app/.env:ro
      - ./sessions:/app/sessions
      - ./temp:/app/temp
      - /storage/comfyui/input:/storage/comfyui/input
      - /storage/comfyui/output:/storage/comfyui/output
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for container management 