version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    network_mode: host  # Use host networking to access ComfyUI
    volumes:
      - ./.env:/app/.env:ro
      - ./sessions:/app/sessions
      - /storage/comfyui/input:/storage/comfyui/input
      - /storage/comfyui/output:/storage/comfyui/output
    user: "${UID:-1000}:${GID:-1000}"  # Use host user's UID/GID 